version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: h2
      DB_URL: jdbc:h2:mem:testdb
      DB_USERNAME: sa
      DB_PASSWORD: sa
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-init-data:/opt/keycloak/data/import
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"

  app:
    build: ./
    ports:
      - "8081:8081"
    depends_on:
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/keycloak
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTERED_CLIENTS: |
        keycloak:
          client-id: spring-boot-app
          client-secret: secret
          authorization-grant-type: client_credentials
          scope: openid,profile,roles
          redirect-uri: http://localhost:8081
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTHORIZE_URI: http://keycloak:8080/realms/demo/protocol/openid-connect/auth
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI: http://key